skip-check:
  # Ensure GitHub repository is Private
  - CKV_GIT_1
  # GitHub pull requests should require at least 2 approvals
  - CKV_GIT_5
  # Issue: https://github.com/bridgecrewio/checkov/issues/3839
  # The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch inputs MUST be empty
  - CKV_GHA_7
