# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/configuration/ and in linters documentation

BASH_SHFMT_ARGUMENTS: --indent 2 --space-redirects

DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK # Using lychee instead
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY
  - SPELL_CSPELL
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TFLINT

# Remove: To receive reports as email, please set variable EMAIL_REPORTER_EMAIL
EMAIL_REPORTER: false

FAIL_IF_MISSING_LINTER_IN_FLAVOR: true

FILTER_REGEX_EXCLUDE: CHANGELOG.md

FORMATTERS_DISABLE_ERRORS: false

MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yml

# Remove initial MegaLinter graphic
PRINT_ALPACA: false

# Disable creating report directory
REPORT_OUTPUT_FOLDER: none

VALIDATE_ALL_CODEBASE: true
