---
npm: false
git:
  changelog: auto-changelog --stdout --append-git-log '--invert-grep --grep=dependabot' --unreleased --commit-limit false --sort-commits date-desc --ignore-commit-pattern "^CHANGELOG|^Merge pull request.*/dependabot/" --template https://raw.githubusercontent.com/release-it/release-it/master/conf/changelog-compact.hbs
  commit: false
  requireCleanWorkingDir: false
  requireCommits: true
  tagName: v${version}
github:
  releaseName: v${version}
  release: true
hooks:
  after:release: |
    test -d .git || ( echo "Run in top level directory" && exit 1 )
    auto-changelog --append-git-log '--invert-grep --grep=dependabot' --commit-limit false --sort-commits date-desc --ignore-commit-pattern "^CHANGELOG|^Merge pull request.*/dependabot/" --template https://raw.githubusercontent.com/release-it/release-it/master/conf/keepachangelog.hbs ;
    git checkout -b "update_changelog"
    git add CHANGELOG.md ;
    git commit -m "CHANGELOG file update" ;
    git push ;
    gh pr create --web --fill
