---
npm: false
git:
  commit: false
  requireCleanWorkingDir: false
  requireCommits: true
  tagName: v${version}
github:
  releaseName: v${version}
  release: true
  autoGenerate: true
hooks:
  before:version:bump: |
    set -euxo pipefail && \
    test -d .git || ( echo "Run in top level directory" && exit 1 ) && \
    auto-changelog --latest-version v${version} --tag-pattern 'v\d+\.\d+\.\d+' --append-git-log '--invert-grep --grep=dependabot' --commit-limit false --sort-commits date-desc --ignore-commit-pattern "^CHANGELOG|^Merge pull request.*/dependabot/" --template https://raw.githubusercontent.com/release-it/release-it/14.14.3/conf/keepachangelog.hbs && \
    git checkout -b "update-changelog" && \
    git add CHANGELOG.md && \
    git commit -m "docs(changelog): CHANGELOG file update [skip ci]" && \
    git push && \
    gh pr merge --rebase "$(gh pr create --fill | grep '^https://github.com/')" && \
    git checkout $(git remote show origin | sed -n '/HEAD branch/s/.*: //p') && \
    git pull -r && \
    git branch -D "update-changelog"
