---
name: renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: "Dry-Run"
      logLevel:
        type: choice
        description: "Log-Level"
        default: debug
        options:
          - info
          - debug
          - trace
  push:
    branches:
      - main
      - "!renovate/*"
  schedule:
    - cron: "0 0,2,4 * * 1"

env:
  # https://docs.renovatebot.com/troubleshooting/#log-debug-levels
  LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
  # https://docs.renovatebot.com/self-hosted-configuration/#repositories
  RENOVATE_REPOSITORIES: ${{ github.repository }}
  # https://docs.renovatebot.com/self-hosted-configuration/#username
  RENOVATE_USERNAME: ${{ github.repository_owner }}
  # https://docs.renovatebot.com/configuration-options/#platformcommit
  RENOVATE_PLATFORM_COMMIT: "true"
  # https://docs.renovatebot.com/self-hosted-configuration/#dryrun
  # Run renovate in dry-run mode if executed in branches other than main - prevents versions in PRs/branches from being updated
  RENOVATE_DRY_RUN: "${{ inputs.dryRun || ( github.head_ref || github.ref_name ) != 'main' || false }}"
  RENOVATE_TOKEN: ${{ github.token }}
  # Workflow updates only works with PATs or GH App
  # https://github.com/orgs/community/discussions/35410

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    concurrency:
      group: renovate
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: 💡 Self-hosted Renovate
        uses: renovatebot/github-action@42c1d3cb1d1ca891765626ba71cdff5e757258de # v40.0.2
