---
name: links

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/links.yml
      - lychee.toml
  schedule:
    - cron: "0 0 * * 1"

permissions: read-all

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Restore lychee cache
        uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: lycheeverse/lychee-action@7da8ec1fc4e01b5a12062ac6c589c10a4ce70d67 # v2.0.0
        with:
          args: ". --exclude-path CHANGELOG.md ${{ steps.pages.outputs.base_url }}"
          fail: true
