name: hugo-build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  hugo-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2
        with:
          hugo-version: latest

      - name: Build
        run: |
          hugo --gc
          cp LICENSE README.md public/
          echo "${{ github.event.repository.name }}" > public/CNAME

      - name: Check broken links
        env:
          EXCLUDE: |
            linkedin.com
        run: |
          export INPUT_URL="https://${{ github.event.repository.name }}"
          export INPUT_PAGES_PATH="public"
          export INPUT_CMD_PARAMS="--buffer-size=8192 --max-connections=10 --color=always --skip-tls-verification --exclude=($( echo "${EXCLUDE}" | tr '\n' '|' ))"
          wget -qO- https://raw.githubusercontent.com/ruzickap/action-my-broken-link-checker/v2/entrypoint.sh | bash

      - name: Deploy
        uses: peaceiris/actions-gh-pages@354d78ff6f3135c9c78c8e5275615a64dacad357 # v3.0.3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
