name: release

on:
  release:
    types: [published]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          submodules: true

      - name: Update repositories
        run: sudo apt update

      - name: Install necessary packages
        run: sudo apt install -y make poppler-utils texlive texlive-latex-extra

      - name: Create the documents
        id: run
        run: |
          ./run.sh
          LATEX_FILENAME=$(ls ./*.tex)
          echo "::set-output name=FILE::${LATEX_FILENAME%.*}"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: |
            ${{ steps.run.outputs.FILE }}.jpg
            ${{ steps.run.outputs.FILE }}.pdf
            ${{ steps.run.outputs.FILE }}.png
            ${{ steps.run.outputs.FILE }}.svg
