name: markdown

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.md"
      - .github/workflows/markdown.yml
  push:
    branches:
      - main
    paths:
      - "**.md"
      - .github/workflows/markdown.yml

jobs:
  markdownlint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@919d3735df9bbc094d206521a774133ec8f3c4ca # v1
        with:
          exclude: |
            CHANGELOG.md

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Link Checker
        uses: ruzickap/action-my-markdown-link-checker@0e91bb575f14ac4710dc6b72bd53b30d00a33cc2 # v1.0.7
        with:
          exclude: |
            CHANGELOG.md
