---
name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4.1.1
        id: release
        with:
          release-type: simple

  latex-build:
    needs: [release-please]
    if: needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          submodules: true

      - name: Run script to build document
        id: build
        run: |
          ./run.sh
          FILE_NAME=$(find ./*.tex | sed 's@^\./\(.*\)\.tex@\1@')
          echo "file_name=${FILE_NAME}" >> "${GITHUB_OUTPUT}"

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euxo pipefail
          gh release upload ${{ needs.release-please.outputs.tag_name }} ${{ steps.build.outputs.file_name }}.*
