name: Lint Commit Messages
on:
  - pull_request

permissions: read-all

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@4caf21aed4a778f940d0b17eb109942ef167bb27 # v5.0.2
