name: github-actions-packages-notification

# This github action only serves for monitoring of new versions by
# .github/dependabot-github-actions.yml

on:
  repository_dispatch:

jobs:
  markdownlint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: accurics/terrascan-action@v1
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.1
      - uses: ansible/ansible-lint-action@v6.0.2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
      - uses: azohra/shell-linter@v0.6.0
      - uses: burdzwastaken/hadolint-action@master
      - uses: checkmarx/kics-action@v1.5
      - uses: docker://ghcr.io/github/super-linter:slim-v4
      - uses: github/codeql-action/upload-sarif@v1
      - uses: github/super-linter/slim@v4
      - uses: hashicorp/setup-terraform@v2
      - uses: haya14busa/action-update-semver@v1
      - uses: ibiqlik/action-yamllint@v3
      - uses: jontze/action-mdbook@v1.1.0
      - uses: peaceiris/actions-gh-pages@v3
      - uses: peaceiris/actions-hugo@v2
      - uses: pre-commit/action@v2.0.6
      - uses: ruzickap/action-my-broken-link-checker@v2
      - uses: ruzickap/action-my-markdown-link-checker@v1
      - uses: ruzickap/action-my-markdown-linter@v1
      - uses: softprops/action-gh-release@v1
      - uses: tfsec/tfsec-sarif-action@v0.1.0

# find ~/git/ -maxdepth 4 -path "*/.github/workflows/*.yml" -type f -exec awk -F' uses: ' '/^\s*uses: \w/ || /^\s*- uses: \w/ { print "      - uses: " $2 }' {} \; | sort | uniq
