name: github-actions-packages-notification

# This github action only serves for monitoring of new versions by
# .github/dependabot-github-actions.yml

on:
  repository_dispatch:

jobs:
  markdownlint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: softprops/action-gh-release@v1
      - uses: ansible/ansible-lint-action@master
      - uses: avto-dev/markdown-lint@v1
      - uses: azohra/shell-linter@v0.6.0
      - uses: burdzwastaken/hadolint-action@master
      - uses: docker://ghcr.io/github/super-linter:slim-v4
      - uses: hashicorp/setup-terraform@v1
      - uses: hashicorp/terraform-github-actions@v0.8.0
      - uses: haya14busa/action-update-semver@v1
      - uses: ibiqlik/action-yamllint@v3
      - uses: peaceiris/actions-gh-pages@v3
      - uses: peaceiris/actions-hugo@v2
      - uses: ruzickap/action-my-markdown-link-checker@v1
      - uses: ruzickap/action-my-markdown-linter@v1

# find ~/git/ -maxdepth 4 -path "*/.github/workflows/*.yml" -type f -exec awk -F' uses: ' '/^\s*uses: \w/ || /^\s*- uses: \w/ { print "      - uses: " $2 }' {} \; | sort | uniq
