name: markdown

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.md"
      - .github/workflows/markdown.yml
  push:
    branches:
      - main
    paths:
      - "**.md"
      - .github/workflows/markdown.yml

permissions: read-all

jobs:
  markdownlint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@befc7350469f96b27db57948a046d20e1884a28f # v1.0.10
        with:
          exclude: |
            CHANGELOG.md

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Link Checker
        uses: ruzickap/action-my-markdown-link-checker@e7e8635735a15a86b081f8255022bcc251cc9003 # v1.2.0
        with:
          exclude: |
            README.md
            CHANGELOG.md
