name: markdown-check

on:
  push:
    branches-ignore:
      - main
    paths:
      - "**.md"
      - .github/workflows/markdown-check.yml
      - .markdownlint.yml

permissions: read-all

jobs:
  markdownlint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@5e4b49fb65d856a021b96ad7f799cc3bde9af91e # v1.3.0
        with:
          exclude: |
            tests/
            CHANGELOG.md

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Link Checker
        uses: ruzickap/action-my-markdown-link-checker@0bc23ed1091ca59159fb6e2bd05112a942fb7f70 # v1.5.0
        with:
          exclude: |
            tests/
            CHANGELOG.md
