name: pre-commit-config

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - "!chore/renovate/*"
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/pre-commit-config.yml

env:
  SKIP: no-commit-to-branch

defaults:
  run:
    shell: bash -euxo pipefail {0}

permissions: read-all

jobs:
  pre-commit-config:
    # brew is not available on ubuntu-24.04-arm
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 1.26

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Install checkov using uv
        run: |
          # renovate: datasource=pypi depName=checkov
          uv tool install checkov==3.3.1
          echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"

      - name: Install dependencies
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> "${GITHUB_PATH}"
          brew install actionlint gitleaks opentofu terraform-docs terrascan tfupdate trivy

          gitleaks version
          terrascan version
          tfupdate --version
          tofu -version
          terraform-docs --version
          trivy version

      - uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # v2.0.4
